<a href="https://colab.research.google.com/github/fesaez/jupyter/blob/master/agregacoesDataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
dados = {
    'id_cliente': [101, 102, 103, 104, 105, 106],
    'valor_venda': np.random.randint (100, 200, 6),
    'regiao': ['norte', 'norte', 'nordeste', 'nordeste', 'nordeste', 'norte']
}

In [18]:
df = pd.DataFrame(dados)
df

   id_cliente  valor_venda    regiao
0         101          135     norte
1         102          198     norte
2         103          161  nordeste
3         104          145  nordeste
4         105          123  nordeste
5         106          141     norte

In [20]:
df.groupby('regiao')['valor_venda'].mean()

regiao
nordeste    143.0
norte       158.0
Name: valor_venda, dtype: float64

In [4]:
import pandas as pd
df_nomes = pd.DataFrame ({
    'id_cliente': [1, 2, 3, 4],
    'nome': ['joao', 'jose', 'maria', 'ana']
})
df_nomes

   id_cliente   nome
0           1   joao
1           2   jose
2           3  maria
3           4    ana

In [5]:
df_vendas = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'quantidade_vendadida': [10, 150, 200, 250]
})
df_vendas

   id_cliente  quantidade_vendadida
0           1                    10
1           2                   150
2           3                   200
3           4                   250

In [7]:
df_nome_venda = pd.merge(df_nomes, df_vendas, on='id_cliente')
df_nome_venda

   id_cliente   nome  quantidade_vendadida
0           1   joao                    10
1           2   jose                   150
2           3  maria                   200
3           4    ana                   250

In [9]:
df_nome_venda_nova = pd.DataFrame({
    'id_cliente':[5],
    'nome': ['tiago'],
    'quantidade_vendido':[100]
})
pd.concat([df_nome_venda, df_nome_venda_nova])

   id_cliente   nome  quantidade_vendadida  quantidade_vendido
0           1   joao                  10.0                 NaN
1           2   jose                 150.0                 NaN
2           3  maria                 200.0                 NaN
3           4    ana                 250.0                 NaN
0           5  tiago                   NaN               100.0